NumPy (Numerical Python) is a powerful open-source library in Python used for numerical and scientific computing. It provides support for large, multi-dimensional arrays and matrices, along with a collection of mathematical functions to operate on these arrays efficiently. NumPy serves as the foundation for many other scientific libraries in Python, such as Pandas, SciPy, and scikit-learn.

Advantages of NumPy array
1. Allows several mathematical operations
2. Fast operations

In [9]:
import numpy as np

List vs Numpy - Time taken

In [29]:
from time import process_time

In [6]:
# Time taken for python_list

python_list = [i for i in range(10000)]

start_time = process_time()

python_list = [i+5 for i in python_list]

end_time = process_time()

print(end_time - start_time)

0.0007948000000004285


In [12]:
# Time taken by a numPy array

np_array = np.array([i for i in range(10000)])

start_time = process_time()

np_array += 5

end_time = process_time()

print (end_time - start_time)




0.0005260229999990429


Data type

In [14]:
# list

list_1 = [1,2,3,4]
print(list_1)
type(list_1)

# numpy_array

np_array =np.array([1,2,3,4])
print(np_array)
type(np_array)

[1, 2, 3, 4]
[1 2 3 4]


numpy.ndarray

In [16]:
# 1D array with numpy array

a = np.array([1,2,3,4,5])

print(a)
a.shape

[1 2 3 4 5]


(5,)

In [20]:
# 2D array with numpy array

b = np.array([(1,2,3,4),(5,6,7,8)])
print(b)
b.shape

[[1 2 3 4]
 [5 6 7 8]]


(2, 4)

In [21]:
# 3D array with numpy array

c = np.array([
    [[1, 2, 3, 4],
     [5, 6, 7, 8],
     [9, 10, 11, 12]],

    [[13, 14, 15, 16],
     [17, 18, 19, 20],
     [21, 22, 23, 24]]
])

print(c)
c.shape



[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]


(2, 3, 4)

In [23]:
# float datatype
d = np.array([(1,2,3,4), (5,6,7,8)], dtype = float)
print(d)

[[1. 2. 3. 4.]
 [5. 6. 7. 8.]]


In [3]:
#Initial placeholder in numPy array
x = np.zeros((4,5))
print(x)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [4]:
# Create numPy array with ones
y = np.ones((3,3))
print(y)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [5]:
# Array with particular values
z = np.full((5,4), 5)
print(z)

[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]


In [7]:
# Create an identity matrix
p = np.eye(4)
print(p)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [11]:
# Create a numpy array with random values
pq = np.random.random((3,4))
print(pq)

[[0.26296071 0.2388526  0.5997989  0.77984986]
 [0.75465615 0.05772393 0.44407628 0.31241607]
 [0.06592716 0.83370178 0.71880541 0.76104616]]


In [12]:
# Random integer values array within a specific range
q = np.random.randint(10,100,(3,5))
print(q)


[[55 67 57 56 86]
 [61 70 84 22 32]
 [31 52 31 82 58]]


In [14]:
# Array of evenly spaced values
d = np.linspace(10,30,5)
print(d)

[10. 15. 20. 25. 30.]


In [15]:
# Array of evenly spaced values -----> specifing the step
e = np.arange(10,30,5)
print(e)

[10 15 20 25]


In [16]:
# Convert a list to numpy array
list_1 = [10, 20, 30, 40, 50]
np_array = np.asarray(list_1)
print(np_array)
type(np_array)

[10 20 30 40 50]


numpy.ndarray

In [19]:
# Analysing a numpy array
c =  np.random.randint(10,90,(5,5))
print(c)

[[50 45 82 87 17]
 [80 24 47 28 78]
 [87 66 18 61 81]
 [57 43 22 16 68]
 [12 58 77 26 20]]


In [23]:
# Array Dimension
print(c.shape)

# Number of dimensions
print(c.ndim)

# Number of elements in an array
print(c.size)

#Check the datatype present in the array

print(c.dtype)

(5, 5)
2
25
int64


In [35]:
# Mathematical operations on a np array
aa = np.random.randint(0, 10, (3,3))
bb = np.random.randint(10, 20, (3,3))
print(aa)
print(bb)
print(aa+bb)
print(aa-bb)
print(aa*bb)
print(aa/bb)

[[3 7 8]
 [5 2 3]
 [9 6 7]]
[[14 17 11]
 [16 13 13]
 [15 19 13]]
[[17 24 19]
 [21 15 16]
 [24 25 20]]
[[-11 -10  -3]
 [-11 -11 -10]
 [ -6 -13  -6]]
[[ 42 119  88]
 [ 80  26  39]
 [135 114  91]]
[[0.21428571 0.41176471 0.72727273]
 [0.3125     0.15384615 0.23076923]
 [0.6        0.31578947 0.53846154]]


In [37]:
# Another way
cc = np.random.randint(20, 30, (3,3))
dd = np.random.randint(10, 20, (3,3))
print(cc)
print(dd)
print (np.add(cc,dd))
print (np.subtract(cc,dd))
print (np.multiply(cc,dd))
print (np.divide(cc,dd))

[[21 27 29]
 [23 25 22]
 [20 28 27]]
[[11 12 19]
 [12 19 19]
 [17 19 14]]
[[32 39 48]
 [35 44 41]
 [37 47 41]]
[[10 15 10]
 [11  6  3]
 [ 3  9 13]]
[[231 324 551]
 [276 475 418]
 [340 532 378]]
[[1.90909091 2.25       1.52631579]
 [1.91666667 1.31578947 1.15789474]
 [1.17647059 1.47368421 1.92857143]]


In [41]:
# Array manipulation
array = np.random.randint(0,10,(2,3))
print(array)
print(array.shape)
tran = np.transpose(array)
print(tran)
print(tran.shape)

# Another way
tran2 = array.T
print(tran2)
print(tran2.shape)

[[0 3 4]
 [4 4 8]]
(2, 3)
[[0 4]
 [3 4]
 [4 8]]
(3, 2)
[[0 4]
 [3 4]
 [4 8]]
(3, 2)


In [43]:
# Reshaping array
rp = np.random.randint(0,10,(2,3))
print(rp)
print(rp.shape)
reshaped = np.reshape(re, (3,2))
print(reshaped)
print(reshaped.shape)

[[9 7 3]
 [0 4 8]]
(2, 3)
[[0 1]
 [7 8]
 [8 9]]
(3, 2)
