In [ ]:
import numpy as np


# Creating a Matrix using numpy

In [ ]:
matrix_1 = np.array([[2, 3],[6, 7]])
print(matrix_1)

[[2 3]
 [6 7]]


In [ ]:
matrix_1.shape

(2, 2)

In [ ]:
matrix_2 = np.array([[10, 35, 45], [50, 64, 80], [20, 15, 90]])
print(matrix_2)

[[10 35 45]
 [50 64 80]
 [20 15 90]]


In [ ]:
matrix_2.shape

(3, 3)

# Creating Matrix with Random Values

In [ ]:
random_matrix = np.random.rand(3,3)
print(random_matrix)

[[0.36197949 0.89228508 0.01755455]
 [0.38300814 0.69645864 0.50974403]
 [0.1384606  0.74550674 0.109669  ]]


In [ ]:
# creating matrix with random integer
random_integer_matrix = np.random.randint(100, size=(4,5))
print(random_integer_matrix)

[[99 37 29 46 32]
 [25 11 91 39 68]
 [43  3 76 56 14]
 [47 15 78 60  9]]


In [ ]:
matrix_3 = np.ones((2,3))
print(matrix_3)

[[1. 1. 1.]
 [1. 1. 1.]]


In [ ]:
matrix_3 = np.ones((2,3), dtype = int)
print(matrix_3)

[[1 1 1]
 [1 1 1]]


In [ ]:
matrix_3 = np.ones((10,10), dtype = int)
print(matrix_3)

[[1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]]


In [ ]:
null_matrix = np.zeros((4,4))
print(null_matrix)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [ ]:
null_matrix = np.zeros((4,4), dtype= int)
print(null_matrix)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


#Identity Matrix

In [ ]:
identity_matrix = np.eye(5,5)
print(identity_matrix)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


# Transpose of a Matrix

In [ ]:
# Matrix with random integer values
a = np.random.randint(100, size=(4,3))
print(a)

[[42  6 48]
 [48 78 13]
 [11 13  0]
 [56 57 18]]


In [ ]:
transpose_of_a = np.transpose(a)
print(transpose_of_a)

[[42 48 11 56]
 [ 6 78 13 57]
 [48 13  0 18]]


# Matrix Operation

Two matrices are added if they have same shape

In [ ]:
# Creating two matrices

A = np.array([[2,3],[4,5]])
B = np.array([[6,7],[8,9]])
sum = A+B
print(sum)

[[ 8 10]
 [12 14]]


In [ ]:
matrix_1 = np.random.randint(10, size=(3,3))
matrix_2 = np.random.randint(10, size=(3,3))
print(matrix_1)
print(matrix_2)
sum_of_matrix = matrix_1 + matrix_2
print(sum_of_matrix)

[[8 7 9]
 [2 3 8]
 [9 1 8]]
[[8 3 5]
 [7 9 9]
 [3 4 0]]
[[16 10 14]
 [ 9 12 17]
 [12  5  8]]


In [ ]:
#sub_of_matrix = matrix_1 - matrix_2
sub_of_matrix = np.subtract(matrix_1, matrix_2)
print(sub_of_matrix)

[[ 0  4  4]
 [-5 -6 -1]
 [ 6 -3  8]]


Multiplying matrix a scaler

In [ ]:
x = 5
y =np.random.randint(10, size = (4,3))
print(y)
product = np.multiply(x,y)
print(product)

[[4 6 0]
 [8 0 1]
 [8 4 6]
 [1 2 0]]
[[20 30  0]
 [40  0  5]
 [40 20 30]
 [ 5 10  0]]


Multiplying 2 matrices

In [ ]:
# create two matrics with random values
matrix_3 = np.random.randint(10, size=(3,3))
matrix_4 = np.random.randint(10, size=(3,3))
print(matrix_3)
print(matrix_4)
product_of_matrics = np.dot(matrix_3, matrix_4)
print(product_of_matrics)

[[9 5 0]
 [7 6 4]
 [1 3 9]]
[[2 2 9]
 [4 2 7]
 [4 0 7]]
[[ 38  28 116]
 [ 54  26 133]
 [ 50   8  93]]
